test/integration/: prereq() to source a script and exit on (x)failure

diff --git a/test/integration/framework-without-repo b/test/integration/framework-without-repo
--- a/test/integration/framework-without-repo
+++ b/test/integration/framework-without-repo
@@ -146,8 +146,6 @@ exitwithstatus() {
 			exit $((EXIT_CODE <= 254 ? EXIT_CODE : 254));
 		elif [ $XFAILED -gt 0 ]; then
 			exit 255
-		else
-			exit 0
 		fi
 }
 
@@ -171,7 +169,16 @@ addtrap() {
 		local -r fmt="$1"; shift
 		printf -v CURRENTTRAP "$fmt %s" "$@" "$CURRENTTRAP"
 	fi
-	trap "shellsetedetector; $CURRENTTRAP exitwithstatus;" 0 HUP INT QUIT ILL ABRT FPE SEGV PIPE TERM
+	trap "shellsetedetector; $CURRENTTRAP exitwithstatus; exit 0;" 0 HUP INT QUIT ILL ABRT FPE SEGV PIPE TERM
+}
+
+# Source a script whose effect is a prerequisite.
+# Do not continue, if that script has failed or x-failed.
+prereq() {
+	. "$1"
+	if [ $EXIT_CODE -gt 0 ] || [ $XFAILED -gt 0 ]; then
+	    exit
+	fi
 }
 
 setupenvironment() {
