fixup! test/integration/run-tests: print failed tests 1-per-line for readability

diff --git a/test/integration/run-tests b/test/integration/run-tests
--- a/test/integration/run-tests
+++ b/test/integration/run-tests
@@ -151,7 +151,7 @@ if [ -n "$XFAILED_TESTS" ]; then
 	echo >&2
 fi
 if [ -n "$FAILED_TESTS" ]; then
-	echo >&2 "Failed tests: $FAILED_TESTS"
+	echo >&2 "Failed tests:"
         for t in $FAILED_TESTS; do echo "$t"; done >&2
 	echo >&2
 else
